#!/usr/bin/env ansible-playbook -i hosts
- hosts: master
  vars:
    - vuls_path: ~/vuls
    - env: test
  roles:
    - YasushiKobayashi.golang
  tasks:
    - include: 'tasks/main.yml'
    - name: set config
      copy:
        src: src/config.toml
