---

- name: set up
  yum: name={{ item  }}
  with_items:
    - sqlite
    - git
    - gcc
    - make
    - yum-plugin-changelog

- name: mkdir vuls log
  file:
    path: /var/log/vuls
    state: directory
    mode: 0755
    owner: '{{ vuls_user }}'

- name: mkdir gopath
  file:
    path: '{{ go_path }}'
    state: directory
  become: false

- name: mkdir kotakanbe
  file:
    path: '{{ go_path  }}/src/github.com/kotakanbe/go-cve-dictionary'
    state: directory
    mode: 0755
  become: false

- name: install go-cve-dictionary
  git:
    repo: https://github.com/kotakanbe/go-cve-dictionary.git
    dest: '{{ go_path }}/src/github.com/kotakanbe/go-cve-dictionary'
  become: false

- name: make cve
  shell: make install
  args:
    chdir: '{{ go_path }}/src/github.com/kotakanbe/go-cve-dictionary'
    executable: /bin/bash
  become: false

- name: install jvn
  shell: for i in `seq 2002 $(date +"%Y")`; do go-cve-dictionary fetchnvd -years $i; done
  args:
    chdir: '{{ go_path }}'
    executable: /bin/bash
  become: false

- name: install jvn japanese
  shell: for i in `seq 1998 $(date +"%Y")`; do go-cve-dictionary fetchjvn -years $i; done
  args:
    chdir: '{{ go_path }}'
    executable: /bin/bash
  become: false

- name: mkdir goval-dictionary
  file:
    path: '{{ go_path }}/src/github.com/kotakanbe/goval-dictionary'
    state: directory
    mode: 0755
  become: false

- name: install goval-dictionary
  git:
    repo: https://github.com/kotakanbe/goval-dictionary.git
    dest: '{{ go_path }}/src/github.com/kotakanbe/goval-dictionary'
  become: false


- name: make goval-dictionary
  shell: make install
  args:
    chdir: '{{ go_path }}/src/github.com/kotakanbe/goval-dictionary'
    executable: /bin/bash
  become: false

- name: mkdir vuls
  file:
    path: '{{ go_path }}/src/github.com/future-architect/vuls'
    state: directory
    mode: 0755
  become: false

- name: install vuls
  git:
    repo: https://github.com/future-architect/vuls.git
    dest: '{{ go_path }}/src/github.com/future-architect/vuls'
  become: false

- name: make vuls
  shell: make install
  args:
    chdir: '{{ go_path }}/src/github.com/future-architect/vuls'
    executable: /bin/bash
  become: false
